import React, { useRef } from "react";
import NewsCard from "./NewsCard";
import FrenchImg from "../../Assets/french proficiency.png";
import Averaged from "../../Assets/average scores accepted.png";
import Right from "../../Assets/application fee hiked.png";
import Working from "../../Assets/working hours increased.png";
import Changes from "../../Assets/processing time and backlog.jpg";
import { MdChevronLeft, MdChevronRight } from "react-icons/md";
const Component4 = () => {
  const sliderRef = useRef(null);

  const newsData = [
    {
      title: "FRENCH PROFICIENCY LEADS CATEGORY-BASED SELECTIONS",
      description:
        "French language proficiency will now be at the forefront of category-based selections in express entry draws in 2024.",
      image: FrenchImg,
    },
    {
      title:
        "AVERAGED LANGUAGE SCORES NOW ACCEPTED UNDER EXPRESS ENTRY FOR DISABLED CANDIDATES",
      description:
        "Averaged language scores generated by the respective language organisation will now be accepted under Express Entry only for candidates living with physical or mental disability.",
      image: Averaged,
    },
    {
      title: "RIGHT OF PERMANENT RESIDENT FEE INCREASED",
      description:
        "Canada's right of permanent residence fee (RPRF) has been significantly increased, with a substantial hike of 12%.",
      image: Right,
    },
    {
      title: "WORKING HOURS INCREASED FOR STUDENTS IN CANADA",
      description:
        "As of April 29th 2024, working hours for students will be increased; for both during academic session and academic breaks.",
      image: Working,
    },
    {
      title: "CHANGES IN FEDERAL BUSINESS PROGRAMS TO TACKLE BACKLOG ISSUE",
      description:
        "Changes have been announced to the Start-up visa and Self-Employed Persons programs to manage backlogs and improve processing time.",
      image: Changes,
    },
  ];

  const slideLeft = () => {
    if (sliderRef.current) {
      sliderRef.current.scrollLeft -= sliderRef.current.offsetWidth;
    }
  };

  const slideRight = () => {
    if (sliderRef.current) {
      sliderRef.current.scrollLeft += sliderRef.current.offsetWidth;
    }
  };

  return (
    <div className="h-auto mt-[7rem] pt-20 px-20 pb-10 bg-gradient-to-r from-white to-slate-50">
      <div className="w-[70%]">
        <div className="text-[3rem] font-semibold mx-[3.8rem] my-4">
          Latest <span className="text-[#019989]">News</span>
        </div>
      </div>
      <div className="flex flex-col ">
        <div
          ref={sliderRef}
          id="slider"
          className="overflow-x-scroll scroll scroll-smooth flex items-center justify-around w-full gap-10 scrollbar-hide"
        >
          {newsData.map((item, index) => (
            <NewsCard key={index} data={item} />
          ))}
        </div>
        <div className="flex items-center justify-end w-full -ml-10 mt-4">
          <MdChevronLeft
            size={30}
            onClick={slideLeft}
            className="cursor-pointer hover:scale-110 mr-8 mt-1 text-black shadow-lg flex items-center bg-white justify-between rounded-[10px] transition ease-in delay-40 duration-200"
          />
          <MdChevronRight
            size={30}
            onClick={slideRight}
            className="cursor-pointer hover:scale-110 mr-8 mt-1 text-black shadow-lg bg-[#00F8E1] flex items-center justify-between rounded-[10px] transition ease-in delay-40 duration-200"
          />
        </div>
      </div>
    </div>
  );
};

export default Component4;
